### ISSUE TITLE
Retrieval Flags Meaning

### ISSUE THREAD

**Issue by DanielOstovary** [vcsjones/OpenOpcSignTool#72]
Hi,

this isnt exactly an issue in OpenOpcSignTool. However, I have seen that when using the CryptRetrieveTimeStamp OpenOpcSignTool uses TIMESTAMP_VERIFY_CONTEXT_SIGNATURE as retrieval flag while according to the documentation (https://docs.microsoft.com/en-us/windows/desktop/api/wincrypt/nf-wincrypt-cryptretrievetimestamp) there is also TIMESTAMP_DONT_HASH_DATA and TIMESTAMP_NO_AUTH_RETRIEVAL. I find the explanation of the flags rather cryptic in the official documentation and don't actually know what the they mean. Can you tell me why I would use which flag?

Kind regards,
Daniel

**Comment by vcsjones** [comment]
Sure.

>TIMESTAMP_DONT_HASH_DATA

Timestamping produces a normal signed CMS over some amount of data. As is always typical of RSA (and other asymmetric algorithms) a hash of the data is what gets signed.

`CryptRetrieveTimeStamp` will hash the input data in `pbData` for you if you do _not_ specify this flag using the hash algorithm specified in `pszHashId`.

If the data you are timestamping is _already_ a hash, then you would want to specify this flag, otherwise the timestamp will be the hash of the hash. OpenOpcSignTool took the approach of having pre-hashed data before performing the actual timestamp.

>TIMESTAMP_VERIFY_CONTEXT_SIGNATURE

Without this flag being set, `CryptRetrieveTimeStamp` will not validate the signature in the CMS that it received from the timestamping server. That is, without this flag, `CryptRetrieveTimeStamp` will just return the CMS without checking that the signature is trusted. If you specify this flag, the the API will do something similar to what `CryptVerifyTimeStampSignature` does as soon as it retrieves the timestamp.

OpenOpcSignTool does not use this flag since this tool is not the judge of the validity of the signature. It's up to the software (typically Visual Studio for most things) to decide if the signature is valid.

>TIMESTAMP_NO_AUTH_RETRIEVAL

This is a somewhat cryptic flag. It's useful if you are working with a timestamping authority that requires authentication to use it, and you do not want the API to automatically authenticate to it. Almost all TSAs are "open" and require no authentication to use (though they certain have things like rate limits). I don't think you will need to use this flag very often, if ever.

**Comment by vcsjones** [comment]
I'm going to close this, feel free to open any more issues if you have questions.
